# Generated by Django 5.1.7 on 2025-07-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moive',
            new_name='Movie',
        ),
    ]
